// DO NOT EDIT THIS FILE
const { resolve } = require('path');

/**
 * @_type { import('@jest/types').Config.InitialOptions }
 * @_type { import('ts-jest').InitialOptionsTsJest }
 * @type { import('ts-jest').JestConfigWithTsJest }
 */
const jestConfig = {
	preset: __dirname,
};

module.exports = jestConfig
