packages:
  - packages/@yarn-tool/*
  - packages/@lazy-node/*
  # all packages in subdirs of packages/ and components/
  - packages/*
  # exclude packages that are inside test/ directories
  - '!**/test/**'

publicHoistPattern:
  - "ts-type"
  - "yargs"
  - "@yarn-tool/*"
  - "@lazy-node/*"
  - "path-is-same"
  - "bluebird"
  - "@ts-type/*"
  - "upath2"
  - "fs-extra"
  - "micromatch"
  - "strip-ansi"


linkWorkspacePackages: true
saveWorkspaceProtocol: false
