import { EnumScriptsEntry } from '../field/scripts';
export declare function defaultWorkspaceRootScripts(): {
    "test:all": string;
    "test:since": string;
    "build:all": string;
    "review:all": string;
    "coverage:all": string;
    "lint:all": string;
    preversion: EnumScriptsEntry;
    postversion: string;
    "lerna:publish": string;
    "lerna:publish:yes": string;
    "prepublishOnly:root": string;
    "prepublishOnly:lockfile": string;
    "prepublishOnly:check-bin": string;
    "prepare:fix-ws-links": string;
    "prepublishOnly:update": string;
    ncu: string;
    "ncu:root": string;
    "ncu:ws": string;
    "sort-package-json": string;
    "sort-package-json:root": string;
    "sort-package-json:ws": string;
    postpublishOnly: string;
    "postpublishOnly:ws-root-changelog": string;
    test: string;
    "test:snapshot:all": string;
    "test:snapshot:since": string;
    "install:reset-lockfile": string;
    "ws:fix-all": string;
    "tsc:showConfig": string;
    "ci:install": string;
    "test:jest:clearCache": string;
    "install:resetLockfile": string;
    "install:frozenLockfile": string;
};
