import { crlf, chkcrlf, R_CRLF, LF } from 'crlf-normalize';

export enum EnumYaenLockBanner
{
	v1 = '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1',
	v2 = '# This file is generated by running "yarn install" inside your project.\n# Manual changes might be lost - proceed with caution!',
}

export function hasBanner(yarnlock_old: Buffer | string)
{
	yarnlock_old = yarnlock_old.toString();

	let lines = yarnlock_old.split(R_CRLF);

	let banners: string[] = [];
	let i = 0;

	for (i = 0; i < lines.length; i++)
	{
		let line = lines[i].trim();

		if (line === '' || line.startsWith('#'))
		{
			banners.push(lines[i])
		}
		else
		{
			break;
		}
	}

	let banner = banners.join(LF).replace(/^\n+|\n+$/g, '');

	if (banner.length > 0)
	{
		banner += '\n\n';
	}

	let content = lines.slice(i).join(LF);

	return {
		banner,
		content,
	}
}

export default hasBanner
