"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.existsYarnLockBanner = exports.EnumYarnLockBanner = void 0;
const crlf_normalize_1 = require("crlf-normalize");
var EnumYarnLockBanner;
(function (EnumYarnLockBanner) {
    EnumYarnLockBanner["v1"] = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1";
    EnumYarnLockBanner["v2"] = "# This file is generated by running \"yarn install\" inside your project.\n# Manual changes might be lost - proceed with caution!";
})(EnumYarnLockBanner = exports.EnumYarnLockBanner || (exports.EnumYarnLockBanner = {}));
function existsYarnLockBanner(yarnlock_old) {
    yarnlock_old = yarnlock_old.toString();
    const lines = yarnlock_old.split(crlf_normalize_1.R_CRLF);
    const banners = [];
    let i = 0;
    for (i = 0; i < lines.length; i++) {
        const line = lines[i].trim();
        if (line === '' || line.startsWith('#')) {
            banners.push(lines[i]);
        }
        else {
            break;
        }
    }
    let banner = banners.join(crlf_normalize_1.LF).replace(/^\n+|\n+$/g, '');
    if (banner.length > 0) {
        banner += '\n\n';
    }
    const content = lines.slice(i).join(crlf_normalize_1.LF);
    return {
        banner,
        content,
    };
}
exports.existsYarnLockBanner = existsYarnLockBanner;
exports.default = existsYarnLockBanner;
//# sourceMappingURL=index.js.map