"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.hasBanner = exports.EnumYaenLockBanner = void 0;
const crlf_normalize_1 = require("crlf-normalize");
var EnumYaenLockBanner;
(function (EnumYaenLockBanner) {
    EnumYaenLockBanner["v1"] = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1";
    EnumYaenLockBanner["v2"] = "# This file is generated by running \"yarn install\" inside your project.\n# Manual changes might be lost - proceed with caution!";
})(EnumYaenLockBanner = exports.EnumYaenLockBanner || (exports.EnumYaenLockBanner = {}));
function hasBanner(yarnlock_old) {
    yarnlock_old = yarnlock_old.toString();
    let lines = yarnlock_old.split(crlf_normalize_1.R_CRLF);
    let banners = [];
    let i = 0;
    for (i = 0; i < lines.length; i++) {
        let line = lines[i].trim();
        if (line === '' || line.startsWith('#')) {
            banners.push(lines[i]);
        }
        else {
            break;
        }
    }
    let banner = banners.join(crlf_normalize_1.LF).replace(/^\n+|\n+$/g, '');
    if (banner.length > 0) {
        banner += '\n\n';
    }
    let content = lines.slice(i).join(crlf_normalize_1.LF);
    return {
        banner,
        content,
    };
}
exports.hasBanner = hasBanner;
exports.default = hasBanner;
//# sourceMappingURL=index.js.map