export declare const enum EnumYarnLockBanner {
    v1 = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1",
    /**
     * @see https://github.com/yarnpkg/berry/blob/4a097fa80c0fc42e3d5eb51c597bf7304e981111/packages/yarnpkg-core/sources/Project.ts#L1739
     */
    v2 = "# This file is generated by running \"yarn install\" inside your project.\n# Manual changes might be lost - proceed with caution!"
}
export declare function existsYarnLockBanner(yarnlock_old: Buffer | string): {
    banner: string;
    content: string;
};
export default existsYarnLockBanner;
