"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.parseYarnLockRawV2Root = void 0;
exports.parseYarnLockRawV2 = parseYarnLockRawV2;
exports.parseYarnLockRawV2Root = parseYarnLockRawV2;
exports.getYarnLockRawV2Root = getYarnLockRawV2Root;
exports.stringifyYarnLockRawV2 = stringifyYarnLockRawV2;
const parsers_1 = require("@yarnpkg/parsers");
function parseYarnLockRawV2(source) {
    return (0, parsers_1.parseSyml)(source === null || source === void 0 ? void 0 : source.toString());
}
function getYarnLockRawV2Root(input) {
    if (('object' in input)) {
        throw new TypeError(`'object' key should not exists in input object`);
    }
    return input;
}
function stringifyYarnLockRawV2(json, noHeader) {
    const list = ["# This file is generated by running \"yarn install\" inside your project.\n# Manual changes might be lost - proceed with caution!" /* EnumYarnLockBanner.v2 */, (0, parsers_1.stringifySyml)(json)];
    if (noHeader) {
        list.shift();
    }
    return list.join("\n" /* EnumLineBreak.LF */ + "\n" /* EnumLineBreak.LF */);
}
//# sourceMappingURL=v2.js.map