name: 'coverage'
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: artiomtr/jest-coverage-report-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          #   threshold: 80 # optional parameter
